"""Small dependency-free Admin interface over the authenticated API."""

from fastapi import APIRouter
from fastapi.responses import HTMLResponse

router = APIRouter(tags=["admin-ui"])

_PAGE = r"""<!doctype html>
<html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>AI My Time — Admin</title><style>
:root{font-family:Inter,system-ui,sans-serif;color:#16202a;background:#f6f8fb}body{margin:0}main{max-width:1180px;margin:auto;padding:28px}h1{margin:0 0 6px}h2{font-size:18px;margin:0 0 12px}.muted{color:#64748b}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(145px,1fr));gap:12px}.card,section,details{background:#fff;border:1px solid #e2e8f0;border-radius:10px;padding:16px;margin-top:18px}.metric{font-size:28px;font-weight:700}summary{cursor:pointer;font-weight:700;font-size:18px}table{width:100%;border-collapse:collapse;font-size:14px}th,td{text-align:left;border-bottom:1px solid #e2e8f0;padding:9px;vertical-align:top}button{background:#0f766e;color:#fff;border:0;border-radius:6px;padding:8px 11px;cursor:pointer;margin:3px}button.secondary{background:#475569}button.danger{background:#b91c1c}input,textarea,select{padding:9px;border:1px solid #cbd5e1;border-radius:6px;margin:3px;max-width:100%;box-sizing:border-box}textarea{display:block;width:100%;min-height:96px}.hidden{display:none}pre{white-space:pre-wrap;overflow:auto;background:#f8fafc;padding:10px;border-radius:6px;max-height:320px}a{color:#0f766e;cursor:pointer}.row{display:flex;flex-wrap:wrap;gap:8px;align-items:center}.pager{margin-top:10px}.person-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:10px}.field{background:#f8fafc;padding:9px;border-radius:6px}.field b{display:block;font-size:12px;color:#64748b;margin-bottom:3px}@media(max-width:650px){main{padding:14px}table{font-size:12px}}
</style></head><body><main>
<header><h1>AI My Time — Admin</h1><div id="identity" class="muted">Вход требуется</div></header>
<section id="login"><h2>Вход</h2><form id="login-form"><input name="email" type="email" placeholder="Электронная почта" required><input name="password" type="password" placeholder="Пароль" required><button>Войти</button></form><button class="secondary" id="reset-button">Восстановить пароль</button><div id="login-error" class="muted"></div></section>
<div id="app" class="hidden"><section><div class="grid" id="dashboard"></div></section>
<details open><summary>Люди</summary><div class="row"><input id="search" placeholder="Имя или Telegram"><button class="secondary" id="search-button">Найти</button></div><div id="people"></div></details>
<details><summary>Консультации</summary><div id="consultations"></div></details>
<details><summary>Внимание</summary><div id="attention"></div></details>
<details><summary>Аудитории</summary><p class="muted">Выборки получателей для рассылок. Сегменты бизнеса находятся в карточке человека.</p><div id="segments"></div></details>
<details open><summary>Рассылки</summary><p class="muted">Отправка возможна только после предпросмотра и явного подтверждения.</p><form id="broadcast-form"><select id="broadcast-audience" required></select><input id="broadcast-title" placeholder="Название рассылки" required><textarea id="broadcast-body" placeholder="Текст сообщения" required></textarea><button>Создать и открыть предпросмотр</button></form><div id="broadcast-flow" class="hidden"></div><div id="broadcasts"></div></details>
<section id="person-panel" class="hidden"><h2>Карточка человека</h2><div id="person"></div></section>
<details><summary>Учётная запись OWNER</summary><p class="muted">Измените адрес входа на ваш рабочий email. Для подтверждения нужен текущий пароль.</p><form id="email-form"><input id="owner-email" type="email" placeholder="Новый email" required><input id="owner-password" type="password" placeholder="Текущий пароль" required><button>Изменить email входа</button></form><div id="email-result" class="muted"></div></details><button class="secondary" id="logout">Выйти</button></div>
</main><script>
const $=id=>document.getElementById(id), PAGE=20, state={people:0,consultations:0,attention:0,segments:0,broadcasts:0,segmentRows:[]};
const esc=v=>String(v??'—').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
const human={new:'Новый',profiling:'Заполнение профиля',diagnostic_in_progress:'Диагностика в процессе',diagnostic_ready:'Диагностика завершена',diagnostic_completed:'Диагностика завершена',consultation_requested:'Запрошена консультация',subscribed:'Получает сообщения',unsubscribed:'Отписан',confirmed:'Подтверждено',revoked:'Отозвано',unknown:'Не подтверждено',allowed:'Доступен в Telegram',blocked:'Недоступен в Telegram',draft:'Черновик',queued:'В очереди',sent:'Отправлено',failed:'Не доставлено',pending:'В очереди',processing:'Отправляется',open:'Открыта',in_progress:'В работе',closed:'Закрыта',normal:'Обычный',high:'Высокий',urgent:'Срочный',recorded:'Зафиксировано',profile_answered:'Получен ответ профиля',diagnostic_started:'Начата диагностика',telegram_delivery:'Доставка в Telegram',message:'Сообщение',consultation_request:'Заявка на консультацию'};
function label(v){return human[v]||String(v??'—').replaceAll('_',' ')} function source(v){return v==='conference_2026'?'Конференция 2026':(v?label(v):'—')} function date(v){return v?new Date(v).toLocaleString('ru-RU'):'—'} function answer(v){return v&&typeof v==='object'&&'value'in v?String(v.value):typeof v==='string'?v:'—'}
function personContact(p){const name=esc(p.display_name||'Без имени');const username=p.telegram_username?.replace(/^@/,'');if(username)return '<a href="https://t.me/'+encodeURIComponent(username)+'" target="_blank" rel="noopener">'+name+' · @'+esc(username)+'</a>';return '<a data-person="'+p.user_id+'">'+name+' · Написать через бота</a>'}
async function api(path,opts={}){const r=await fetch(path,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(opts.headers||{})},...opts});if(!r.ok)throw new Error((await r.json().catch(()=>({detail:r.statusText}))).detail||r.statusText);return r.status===204?null:r.json()}
function table(rows,cols){if(!rows.length)return '<p class="muted">Нет данных</p>';return '<table><thead><tr>'+cols.map(c=>'<th>'+c[0]+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+cols.map(c=>'<td>'+(typeof c[1]==='function'?c[1](r):esc(r[c[1]]))+'</td>').join('')+'</tr>').join('')+'</tbody></table>'}
function pager(kind,count){const disabledPrev=state[kind]===0?'disabled':'';const disabledNext=count<PAGE?'disabled':'';return '<div class="pager"><button class="secondary" data-page="'+kind+'" data-delta="-20" '+disabledPrev+'>Назад</button><button class="secondary" data-page="'+kind+'" data-delta="20" '+disabledNext+'>Далее</button></div>'}
function bind(){document.querySelectorAll('[data-person]').forEach(x=>x.onclick=()=>person(x.dataset.person));document.querySelectorAll('[data-page]').forEach(x=>x.onclick=()=>{state[x.dataset.page]=Math.max(0,state[x.dataset.page]+Number(x.dataset.delta));loadLists()});document.querySelectorAll('[data-preview]').forEach(x=>x.onclick=()=>preview(x.dataset.preview));}
async function loadLists(){const q=$('search').value?'&search='+encodeURIComponent($('search').value):'';const [p,c,a,s,b]=await Promise.all([api('/admin/people?limit='+PAGE+'&offset='+state.people+q),api('/admin/consultations?limit='+PAGE+'&offset='+state.consultations),api('/admin/attention?limit='+PAGE+'&offset='+state.attention),api('/admin/segments?limit='+PAGE+'&offset='+state.segments),api('/admin/broadcasts?limit='+PAGE+'&offset='+state.broadcasts)]);state.segmentRows=s.items;$('people').innerHTML=table(p.items,[['Имя',x=>'<a data-person="'+x.user_id+'">'+esc(x.display_name||'Без имени')+'</a>'],['Telegram',x=>x.telegram_username?'<a href="https://t.me/'+encodeURIComponent(x.telegram_username.replace(/^@/,''))+'" target="_blank" rel="noopener">@'+esc(x.telegram_username.replace(/^@/,''))+'</a>':'Через бота в карточке'],['Этап',x=>label(x.lifecycle_stage)],['Диагностика',x=>label(x.diagnostic_status)],['Консультация',x=>label(x.consultation_status)],['Внимание','attention_count']])+pager('people',p.items.length);$('consultations').innerHTML=table(c.items,[['Человек',x=>personContact(x.person)],['Создана',x=>date(x.created_at)],['Статус',x=>label(x.status)],['Источник',x=>source(x.source)]])+pager('consultations',c.items.length);$('attention').innerHTML=table(a.items,[['Человек',x=>personContact(x.person)],['Причина',x=>esc(x.reason)],['Приоритет',x=>label(x.priority)],['Статус',x=>label(x.status)],['Создано',x=>date(x.created_at)]])+pager('attention',a.items.length);$('segments').innerHTML=table(s.items,[['Аудитория','title'],['Получателей',x=>x.eligible_count]])+pager('segments',s.items.length);$('broadcast-audience').innerHTML='<option value="">Выберите аудиторию</option>'+s.items.map(x=>'<option value="'+x.segment_id+'">'+esc(x.title)+' — '+x.eligible_count+' получ.</option>').join('');$('broadcasts').innerHTML=table(b.items,[['Название','title'],['Статус',x=>label(x.status)],['Получателей','eligible_count'],['В очереди','queued_count'],['Отправлено','sent_count'],['Не доставлено','failed_count'],['Действие',x=>'<button class="secondary" data-preview="'+x.broadcast_id+'">Открыть</button>']])+pager('broadcasts',b.items.length);bind()}
async function load(){const d=await api('/admin/dashboard');$('dashboard').innerHTML=[['Новые люди',d.new_people],['Диагностики начаты',d.started_diagnostics],['Диагностики завершены',d.completed_diagnostics],['Заявки',d.consultation_requests],['Внимание',d.attention_items]].map(x=>'<div class="card"><div class="muted">'+x[0]+'</div><div class="metric">'+x[1]+'</div></div>').join('');await loadLists()}
async function person(id){const [data,trace]=await Promise.all([api('/admin/people/'+id),api('/admin/logs/people/'+id)]),p=data.person,username=p.telegram_username?.replace(/^@/,'');const contact=username?'<a href="https://t.me/'+encodeURIComponent(username)+'" target="_blank" rel="noopener">Написать в Telegram (@'+esc(username)+')</a>':'Через бота';const diagnostics=data.diagnostics.map(x=>'<li>'+label(x.status)+' · '+date(x.completed_at||x.created_at)+(x.summary?'<br>'+esc(x.summary):'')+'</li>').join('')||'<li>Нет</li>';const history=trace.items.map(x=>'<li>'+date(x.occurred_at)+' · '+label(x.event_type)+' · '+label(x.status)+'</li>').join('')||'<li>Нет событий</li>';$('person-panel').classList.remove('hidden');$('person').innerHTML='<div class="person-grid"><div class="field"><b>Имя</b>'+esc(p.display_name||'Не указано')+'</div><div class="field"><b>Telegram</b>'+contact+'</div><div class="field"><b>Телефон</b>Не указан</div><div class="field"><b>Источник</b>'+source(p.source)+'</div><div class="field"><b>Кампания</b>'+source(p.conference_code)+'</div><div class="field"><b>Этап</b>'+label(p.lifecycle_stage)+'</div><div class="field"><b>Сегмент бизнеса</b>'+esc(answer(data.profile_answers.business_type))+'</div><div class="field"><b>Consent для рассылок</b>'+label(p.marketing_consent_status)+'</div><div class="field"><b>Доступность Telegram</b>'+label(p.telegram_reachability)+'</div><div class="field"><b>Статус консультации</b>'+label(p.consultation_status)+'</div></div>'+(username?'':'<h3>Написать через бота</h3><form id="telegram-message-form"><textarea id="telegram-message-text" placeholder="Сообщение человеку" required></textarea><button>Поставить сообщение в очередь</button><div id="telegram-message-result" class="muted"></div></form>')+'<h3>Диагностика и результат</h3><ul>'+diagnostics+'</ul><h3>История</h3><ul>'+history+'</ul><details><summary>Технические данные</summary><pre>'+esc(JSON.stringify(data,null,2))+'</pre></details>';const form=$('telegram-message-form');if(form)form.onsubmit=async e=>{e.preventDefault();if(!confirm('Отправить это сообщение через бота?'))return;try{await api('/admin/people/'+id+'/telegram-message',{method:'POST',body:JSON.stringify({text:$('telegram-message-text').value})});$('telegram-message-result').textContent='Сообщение поставлено в очередь.'}catch(err){$('telegram-message-result').textContent='Не удалось поставить сообщение: '+err.message}};window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'})}
async function preview(id){const x=await api('/admin/broadcasts/'+id+'/preview');$('broadcast-flow').classList.remove('hidden');$('broadcast-flow').innerHTML='<section><h3>Предпросмотр: '+esc(x.title)+'</h3><p>'+esc(x.body).replaceAll('\n','<br>')+'</p><p><b>Получателей:</b> '+x.eligible_count+'</p><p class="muted">Перед отправкой доступность и consent будут проверены повторно.</p><button id="confirm-send">Подтвердить отправку</button><div id="flow-result" class="muted"></div></section>';$('confirm-send').onclick=async()=>{if(!confirm('Отправить эту рассылку '+x.eligible_count+' получателям?'))return;try{const result=await api('/admin/broadcasts/'+id+'/confirm-send',{method:'POST'});$('flow-result').textContent='Рассылка поставлена в очередь: '+result.queued_count+'. Отправлено: '+result.sent_count+'. Не доставлено: '+result.failed_count+'.';await loadLists()}catch(e){$('flow-result').textContent='Не удалось подтвердить отправку: '+e.message}}}
$('broadcast-form').onsubmit=async e=>{e.preventDefault();try{const x=await api('/admin/broadcasts/drafts',{method:'POST',body:JSON.stringify({segment_id:$('broadcast-audience').value,title:$('broadcast-title').value,body:$('broadcast-body').value})});await preview(x.broadcast_id);await loadLists()}catch(err){alert('Не удалось создать рассылку: '+err.message)}};$('search-button').onclick=()=>{state.people=0;loadLists()};$('logout').onclick=async()=>{await api('/admin/auth/logout',{method:'POST',headers:{Origin:location.origin}});location.reload()};$('reset-button').onclick=()=>{$('login-error').textContent='Восстановление пароля пока недоступно: для безопасной отправки ссылки нужен настроенный почтовый канал.'};
async function ready(){try{const me=await api('/admin/auth/me');$('identity').textContent=me.email+' · Владелец';$('owner-email').value=me.email;$('login').classList.add('hidden');$('app').classList.remove('hidden');await load();return true}catch{return false}}$('login-form').onsubmit=async e=>{e.preventDefault();$('login-error').textContent='';try{const f=new FormData(e.target);await api('/admin/auth/login',{method:'POST',body:JSON.stringify(Object.fromEntries(f))});if(!await ready())throw new Error('Сессия не установлена. Обновите страницу и попробуйте ещё раз.');}catch(err){$('login-error').textContent='Не удалось войти: '+err.message}};$('email-form').onsubmit=async e=>{e.preventDefault();try{const me=await api('/admin/auth/me/email',{method:'PATCH',body:JSON.stringify({email:$('owner-email').value,password:$('owner-password').value})});$('identity').textContent=me.email+' · Владелец';$('owner-password').value='';$('email-result').textContent='Адрес входа обновлён.'}catch(err){$('email-result').textContent='Не удалось изменить адрес: '+err.message}};ready();
</script></body></html>"""


@router.get("/admin/", include_in_schema=False, response_class=HTMLResponse)
async def admin_ui() -> HTMLResponse:
    return HTMLResponse(_PAGE, headers={"Cache-Control": "no-store"})
